$(OBJ_RELEASE_DIR)\Guids$(FILE_SUFFIX_BASE).c: Classes\Guids.bas

$(OBJ_DEBUG_DIR)\Guids$(FILE_SUFFIX_BASE).c: Classes\Guids.bas


$(OBJ_RELEASE_DIR)\ArrayStringWriter$(FILE_SUFFIX_CONSOLE).c: Classes\ArrayStringWriter.bas Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ContainerOf.bi Modules\Logger.bi Headers\StringConstants.bi

$(OBJ_DEBUG_DIR)\ArrayStringWriter$(FILE_SUFFIX_CONSOLE).c:   Classes\ArrayStringWriter.bas Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ContainerOf.bi Modules\Logger.bi Headers\StringConstants.bi

$(OBJ_RELEASE_DIR)\ArrayStringWriter$(FILE_SUFFIX_SERVICE).c: Classes\ArrayStringWriter.bas Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ContainerOf.bi Modules\Logger.bi Headers\StringConstants.bi

$(OBJ_DEBUG_DIR)\ArrayStringWriter$(FILE_SUFFIX_SERVICE).c:   Classes\ArrayStringWriter.bas Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ContainerOf.bi Modules\Logger.bi Headers\StringConstants.bi

$(OBJ_RELEASE_DIR)\ArrayStringWriter$(FILE_SUFFIX_TEST).c: Classes\ArrayStringWriter.bas Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ContainerOf.bi Modules\Logger.bi Headers\StringConstants.bi

$(OBJ_DEBUG_DIR)\ArrayStringWriter$(FILE_SUFFIX_TEST).c:   Classes\ArrayStringWriter.bas Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ContainerOf.bi Modules\Logger.bi Headers\StringConstants.bi


$(OBJ_RELEASE_DIR)\AsyncResult$(FILE_SUFFIX_CONSOLE).c: Classes\AsyncResult.bas Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\AsyncResult$(FILE_SUFFIX_CONSOLE).c:   Classes\AsyncResult.bas Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\AsyncResult$(FILE_SUFFIX_SERVICE).c: Classes\AsyncResult.bas Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\AsyncResult$(FILE_SUFFIX_SERVICE).c:   Classes\AsyncResult.bas Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\AsyncResult$(FILE_SUFFIX_TEST).c: Classes\AsyncResult.bas Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\AsyncResult$(FILE_SUFFIX_TEST).c:   Classes\AsyncResult.bas Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\ClientRequest$(FILE_SUFFIX_CONSOLE).c: Classes\ClientRequest.bas Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ClientUri.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\ClientRequest$(FILE_SUFFIX_CONSOLE).c:   Classes\ClientRequest.bas Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ClientUri.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\ClientRequest$(FILE_SUFFIX_SERVICE).c: Classes\ClientRequest.bas Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ClientUri.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\ClientRequest$(FILE_SUFFIX_SERVICE).c:   Classes\ClientRequest.bas Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ClientUri.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\ClientRequest$(FILE_SUFFIX_TEST).c: Classes\ClientRequest.bas Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ClientUri.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\ClientRequest$(FILE_SUFFIX_TEST).c:   Classes\ClientRequest.bas Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ClientUri.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\ClientUri$(FILE_SUFFIX_CONSOLE).c: Classes\ClientUri.bas Classes\ClientUri.bi Interfaces\IClientUri.bi Interfaces\IString.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Http.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\ClientUri$(FILE_SUFFIX_CONSOLE).c:   Classes\ClientUri.bas Classes\ClientUri.bi Interfaces\IClientUri.bi Interfaces\IString.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Http.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\ClientUri$(FILE_SUFFIX_SERVICE).c: Classes\ClientUri.bas Classes\ClientUri.bi Interfaces\IClientUri.bi Interfaces\IString.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Http.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\ClientUri$(FILE_SUFFIX_SERVICE).c:   Classes\ClientUri.bas Classes\ClientUri.bi Interfaces\IClientUri.bi Interfaces\IString.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Http.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\ClientUri$(FILE_SUFFIX_TEST).c: Classes\ClientUri.bas Classes\ClientUri.bi Interfaces\IClientUri.bi Interfaces\IString.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Http.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\ClientUri$(FILE_SUFFIX_TEST).c:   Classes\ClientUri.bas Classes\ClientUri.bi Interfaces\IClientUri.bi Interfaces\IString.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Http.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\CreateInstance$(FILE_SUFFIX_CONSOLE).c: Classes\CreateInstance.bas Classes\CreateInstance.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IBaseStream.bi Classes\ClientUri.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Mime.bi Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Classes\HttpReader.bi Classes\HttpWriter.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\WebServer.bi Interfaces\IRunnable.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Classes\WebSite.bi Classes\WebSiteCollection.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi

$(OBJ_DEBUG_DIR)\CreateInstance$(FILE_SUFFIX_CONSOLE).c:   Classes\CreateInstance.bas Classes\CreateInstance.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IBaseStream.bi Classes\ClientUri.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Mime.bi Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Classes\HttpReader.bi Classes\HttpWriter.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\WebServer.bi Interfaces\IRunnable.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Classes\WebSite.bi Classes\WebSiteCollection.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi

$(OBJ_RELEASE_DIR)\CreateInstance$(FILE_SUFFIX_SERVICE).c: Classes\CreateInstance.bas Classes\CreateInstance.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IBaseStream.bi Classes\ClientUri.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Mime.bi Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Classes\HttpReader.bi Classes\HttpWriter.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\WebServer.bi Interfaces\IRunnable.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Classes\WebSite.bi Classes\WebSiteCollection.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi

$(OBJ_DEBUG_DIR)\CreateInstance$(FILE_SUFFIX_SERVICE).c:   Classes\CreateInstance.bas Classes\CreateInstance.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IBaseStream.bi Classes\ClientUri.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Mime.bi Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Classes\HttpReader.bi Classes\HttpWriter.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\WebServer.bi Interfaces\IRunnable.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Classes\WebSite.bi Classes\WebSiteCollection.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi

$(OBJ_RELEASE_DIR)\CreateInstance$(FILE_SUFFIX_TEST).c: Classes\CreateInstance.bas Classes\CreateInstance.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IBaseStream.bi Classes\ClientUri.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Mime.bi Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Classes\HttpReader.bi Classes\HttpWriter.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\WebServer.bi Interfaces\IRunnable.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Classes\WebSite.bi Classes\WebSiteCollection.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi

$(OBJ_DEBUG_DIR)\CreateInstance$(FILE_SUFFIX_TEST).c:   Classes\CreateInstance.bas Classes\CreateInstance.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\AsyncResult.bi Interfaces\IAsyncResult.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IBaseStream.bi Classes\ClientUri.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Mime.bi Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Classes\HttpReader.bi Classes\HttpWriter.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\WebServer.bi Interfaces\IRunnable.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Classes\WebSite.bi Classes\WebSiteCollection.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi


$(OBJ_RELEASE_DIR)\FileBuffer$(FILE_SUFFIX_CONSOLE).c: Classes\FileBuffer.bas Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi

$(OBJ_DEBUG_DIR)\FileBuffer$(FILE_SUFFIX_CONSOLE).c:   Classes\FileBuffer.bas Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi

$(OBJ_RELEASE_DIR)\FileBuffer$(FILE_SUFFIX_SERVICE).c: Classes\FileBuffer.bas Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi

$(OBJ_DEBUG_DIR)\FileBuffer$(FILE_SUFFIX_SERVICE).c:   Classes\FileBuffer.bas Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi

$(OBJ_RELEASE_DIR)\FileBuffer$(FILE_SUFFIX_TEST).c: Classes\FileBuffer.bas Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi

$(OBJ_DEBUG_DIR)\FileBuffer$(FILE_SUFFIX_TEST).c:   Classes\FileBuffer.bas Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi


$(OBJ_RELEASE_DIR)\HeapBSTR$(FILE_SUFFIX_CONSOLE).c: Classes\HeapBSTR.bas Classes\HeapBSTR.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HeapBSTR$(FILE_SUFFIX_CONSOLE).c:   Classes\HeapBSTR.bas Classes\HeapBSTR.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\HeapBSTR$(FILE_SUFFIX_SERVICE).c: Classes\HeapBSTR.bas Classes\HeapBSTR.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HeapBSTR$(FILE_SUFFIX_SERVICE).c:   Classes\HeapBSTR.bas Classes\HeapBSTR.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\HeapBSTR$(FILE_SUFFIX_TEST).c: Classes\HeapBSTR.bas Classes\HeapBSTR.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HeapBSTR$(FILE_SUFFIX_TEST).c:   Classes\HeapBSTR.bas Classes\HeapBSTR.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).c: Classes\HeapMemoryAllocator.bas Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).c:   Classes\HeapMemoryAllocator.bas Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\HeapMemoryAllocator$(FILE_SUFFIX_SERVICE).c: Classes\HeapMemoryAllocator.bas Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HeapMemoryAllocator$(FILE_SUFFIX_SERVICE).c:   Classes\HeapMemoryAllocator.bas Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\HeapMemoryAllocator$(FILE_SUFFIX_TEST).c: Classes\HeapMemoryAllocator.bas Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HeapMemoryAllocator$(FILE_SUFFIX_TEST).c:   Classes\HeapMemoryAllocator.bas Classes\HeapMemoryAllocator.bi Interfaces\IHeapMemoryAllocator.bi Classes\ContainerOf.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\HttpGetProcessor$(FILE_SUFFIX_CONSOLE).c: Classes\HttpGetProcessor.bas Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi
 
$(OBJ_DEBUG_DIR)\HttpGetProcessor$(FILE_SUFFIX_CONSOLE).c:   Classes\HttpGetProcessor.bas Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi

$(OBJ_RELEASE_DIR)\HttpGetProcessor$(FILE_SUFFIX_SERVICE).c: Classes\HttpGetProcessor.bas Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi

$(OBJ_DEBUG_DIR)\HttpGetProcessor$(FILE_SUFFIX_SERVICE).c:   Classes\HttpGetProcessor.bas Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi

$(OBJ_RELEASE_DIR)\HttpGetProcessor$(FILE_SUFFIX_TEST).c: Classes\HttpGetProcessor.bas Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi

$(OBJ_DEBUG_DIR)\HttpGetProcessor$(FILE_SUFFIX_TEST).c:   Classes\HttpGetProcessor.bas Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi


$(OBJ_RELEASE_DIR)\HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).c: Classes\HttpProcessorCollection.bas Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi
 
$(OBJ_DEBUG_DIR)\HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).c:   Classes\HttpProcessorCollection.bas Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\HttpProcessorCollection$(FILE_SUFFIX_SERVICE).c: Classes\HttpProcessorCollection.bas Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HttpProcessorCollection$(FILE_SUFFIX_SERVICE).c:   Classes\HttpProcessorCollection.bas Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\HttpProcessorCollection$(FILE_SUFFIX_TEST).c: Classes\HttpProcessorCollection.bas Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HttpProcessorCollection$(FILE_SUFFIX_TEST).c:   Classes\HttpProcessorCollection.bas Classes\HttpProcessorCollection.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\HttpReader$(FILE_SUFFIX_CONSOLE).c: Classes\HttpReader.bas Classes\HttpReader.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Http.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HttpReader$(FILE_SUFFIX_CONSOLE).c:   Classes\HttpReader.bas Classes\HttpReader.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Http.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\HttpReader$(FILE_SUFFIX_SERVICE).c: Classes\HttpReader.bas Classes\HttpReader.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Http.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HttpReader$(FILE_SUFFIX_SERVICE).c:   Classes\HttpReader.bas Classes\HttpReader.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Http.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\HttpReader$(FILE_SUFFIX_TEST).c: Classes\HttpReader.bas Classes\HttpReader.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Http.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HttpReader$(FILE_SUFFIX_TEST).c:   Classes\HttpReader.bas Classes\HttpReader.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IString.bi Classes\ContainerOf.bi Modules\Http.bi Classes\HeapBSTR.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\HttpWriter$(FILE_SUFFIX_CONSOLE).c: Classes\HttpWriter.bas Classes\HttpWriter.bi Interfaces\IHttpWriter.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IServerResponse.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HttpWriter$(FILE_SUFFIX_CONSOLE).c:   Classes\HttpWriter.bas Classes\HttpWriter.bi Interfaces\IHttpWriter.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IServerResponse.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\HttpWriter$(FILE_SUFFIX_SERVICE).c: Classes\HttpWriter.bas Classes\HttpWriter.bi Interfaces\IHttpWriter.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IServerResponse.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HttpWriter$(FILE_SUFFIX_SERVICE).c:   Classes\HttpWriter.bas Classes\HttpWriter.bi Interfaces\IHttpWriter.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IServerResponse.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\HttpWriter$(FILE_SUFFIX_TEST).c: Classes\HttpWriter.bas Classes\HttpWriter.bi Interfaces\IHttpWriter.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IServerResponse.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\HttpWriter$(FILE_SUFFIX_TEST).c:   Classes\HttpWriter.bas Classes\HttpWriter.bi Interfaces\IHttpWriter.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IServerResponse.bi Classes\ContainerOf.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\IniConfiguration$(FILE_SUFFIX_CONSOLE).c: Classes\IniConfiguration.bas Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Classes\HttpProcessorCollection.bi Modules\Logger.bi Headers\StringConstants.bi Classes\WebSite.bi Classes\WebSiteCollection.bi

$(OBJ_DEBUG_DIR)\IniConfiguration$(FILE_SUFFIX_CONSOLE).c:   Classes\IniConfiguration.bas Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Classes\HttpProcessorCollection.bi Modules\Logger.bi Headers\StringConstants.bi Classes\WebSite.bi Classes\WebSiteCollection.bi

$(OBJ_RELEASE_DIR)\IniConfiguration$(FILE_SUFFIX_SERVICE).c: Classes\IniConfiguration.bas Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Classes\HttpProcessorCollection.bi Modules\Logger.bi Headers\StringConstants.bi Classes\WebSite.bi Classes\WebSiteCollection.bi

$(OBJ_DEBUG_DIR)\IniConfiguration$(FILE_SUFFIX_SERVICE).c:   Classes\IniConfiguration.bas Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Classes\HttpProcessorCollection.bi Modules\Logger.bi Headers\StringConstants.bi Classes\WebSite.bi Classes\WebSiteCollection.bi

$(OBJ_RELEASE_DIR)\IniConfiguration$(FILE_SUFFIX_TEST).c: Classes\IniConfiguration.bas Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Classes\HttpProcessorCollection.bi Modules\Logger.bi Headers\StringConstants.bi Classes\WebSite.bi Classes\WebSiteCollection.bi

$(OBJ_DEBUG_DIR)\IniConfiguration$(FILE_SUFFIX_TEST).c:   Classes\IniConfiguration.bas Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IServerResponse.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Classes\HttpGetProcessor.bi Interfaces\IHttpGetAsyncProcessor.bi Classes\HttpProcessorCollection.bi Modules\Logger.bi Headers\StringConstants.bi Classes\WebSite.bi Classes\WebSiteCollection.bi


$(OBJ_RELEASE_DIR)\MemoryBuffer$(FILE_SUFFIX_CONSOLE).c: Classes\MemoryBuffer.bas Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\MemoryBuffer$(FILE_SUFFIX_CONSOLE).c:   Classes\MemoryBuffer.bas Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\MemoryBuffer$(FILE_SUFFIX_SERVICE).c: Classes\MemoryBuffer.bas Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\MemoryBuffer$(FILE_SUFFIX_SERVICE).c:   Classes\MemoryBuffer.bas Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\MemoryBuffer$(FILE_SUFFIX_TEST).c: Classes\MemoryBuffer.bas Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\MemoryBuffer$(FILE_SUFFIX_TEST).c:   Classes\MemoryBuffer.bas Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ContainerOf.bi Classes\HeapBSTR.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\NetworkStream$(FILE_SUFFIX_CONSOLE).c: Classes\NetworkStream.bas Classes\NetworkStream.bi Interfaces\INetworkStream.bi Interfaces\IBaseStream.bi Interfaces\IAsyncResult.bi Classes\AsyncResult.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Modules\Logger.bi Modules\Network.bi
 
$(OBJ_DEBUG_DIR)\NetworkStream$(FILE_SUFFIX_CONSOLE).c:   Classes\NetworkStream.bas Classes\NetworkStream.bi Interfaces\INetworkStream.bi Interfaces\IBaseStream.bi Interfaces\IAsyncResult.bi Classes\AsyncResult.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Modules\Logger.bi Modules\Network.bi

$(OBJ_RELEASE_DIR)\NetworkStream$(FILE_SUFFIX_SERVICE).c: Classes\NetworkStream.bas Classes\NetworkStream.bi Interfaces\INetworkStream.bi Interfaces\IBaseStream.bi Interfaces\IAsyncResult.bi Classes\AsyncResult.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Modules\Logger.bi Modules\Network.bi

$(OBJ_DEBUG_DIR)\NetworkStream$(FILE_SUFFIX_SERVICE).c:   Classes\NetworkStream.bas Classes\NetworkStream.bi Interfaces\INetworkStream.bi Interfaces\IBaseStream.bi Interfaces\IAsyncResult.bi Classes\AsyncResult.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Modules\Logger.bi Modules\Network.bi

$(OBJ_RELEASE_DIR)\NetworkStream$(FILE_SUFFIX_TEST).c: Classes\NetworkStream.bas Classes\NetworkStream.bi Interfaces\INetworkStream.bi Interfaces\IBaseStream.bi Interfaces\IAsyncResult.bi Classes\AsyncResult.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Modules\Logger.bi Modules\Network.bi

$(OBJ_DEBUG_DIR)\NetworkStream$(FILE_SUFFIX_TEST).c:   Classes\NetworkStream.bas Classes\NetworkStream.bi Interfaces\INetworkStream.bi Interfaces\IBaseStream.bi Interfaces\IAsyncResult.bi Classes\AsyncResult.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Modules\Logger.bi Modules\Network.bi


$(OBJ_RELEASE_DIR)\ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).c: Classes\ReadRequestAsyncTask.bas Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi
 
$(OBJ_DEBUG_DIR)\ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).c:   Classes\ReadRequestAsyncTask.bas Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi

$(OBJ_RELEASE_DIR)\ReadRequestAsyncTask$(FILE_SUFFIX_SERVICE).c: Classes\ReadRequestAsyncTask.bas Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi

$(OBJ_DEBUG_DIR)\ReadRequestAsyncTask$(FILE_SUFFIX_SERVICE).c:   Classes\ReadRequestAsyncTask.bas Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi

$(OBJ_RELEASE_DIR)\ReadRequestAsyncTask$(FILE_SUFFIX_TEST).c: Classes\ReadRequestAsyncTask.bas Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi

$(OBJ_DEBUG_DIR)\ReadRequestAsyncTask$(FILE_SUFFIX_TEST).c:   Classes\ReadRequestAsyncTask.bas Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi


$(OBJ_RELEASE_DIR)\ServerResponse$(FILE_SUFFIX_CONSOLE).c: Classes\ServerResponse.bas Classes\ServerResponse.bi Interfaces\IServerResponse.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi

$(OBJ_DEBUG_DIR)\ServerResponse$(FILE_SUFFIX_CONSOLE).c:   Classes\ServerResponse.bas Classes\ServerResponse.bi Interfaces\IServerResponse.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi

$(OBJ_RELEASE_DIR)\ServerResponse$(FILE_SUFFIX_SERVICE).c: Classes\ServerResponse.bas Classes\ServerResponse.bi Interfaces\IServerResponse.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi

$(OBJ_DEBUG_DIR)\ServerResponse$(FILE_SUFFIX_SERVICE).c:   Classes\ServerResponse.bas Classes\ServerResponse.bi Interfaces\IServerResponse.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi

$(OBJ_RELEASE_DIR)\ServerResponse$(FILE_SUFFIX_TEST).c: Classes\ServerResponse.bas Classes\ServerResponse.bi Interfaces\IServerResponse.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi

$(OBJ_DEBUG_DIR)\ServerResponse$(FILE_SUFFIX_TEST).c:   Classes\ServerResponse.bas Classes\ServerResponse.bi Interfaces\IServerResponse.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Modules\Logger.bi Headers\StringConstants.bi Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi


$(OBJ_RELEASE_DIR)\ThreadPool$(FILE_SUFFIX_CONSOLE).c: Classes\ThreadPool.bas Classes\ThreadPool.bi Interfaces\IThreadPool.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\ThreadPool$(FILE_SUFFIX_CONSOLE).c:   Classes\ThreadPool.bas Classes\ThreadPool.bi Interfaces\IThreadPool.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\ThreadPool$(FILE_SUFFIX_SERVICE).c: Classes\ThreadPool.bas Classes\ThreadPool.bi Interfaces\IThreadPool.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\ThreadPool$(FILE_SUFFIX_SERVICE).c:   Classes\ThreadPool.bas Classes\ThreadPool.bi Interfaces\IThreadPool.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\ThreadPool$(FILE_SUFFIX_TEST).c: Classes\ThreadPool.bas Classes\ThreadPool.bi Interfaces\IThreadPool.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\ThreadPool$(FILE_SUFFIX_TEST).c:   Classes\ThreadPool.bas Classes\ThreadPool.bi Interfaces\IThreadPool.bi Interfaces\IAsyncIoTask.bi Interfaces\IAsyncResult.bi Classes\ContainerOf.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\WebServer$(FILE_SUFFIX_CONSOLE).c: Classes\WebServer.bas Classes\WebServer.bi Interfaces\IRunnable.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HttpReader.bi Modules\Logger.bi Modules\Network.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi
 
$(OBJ_DEBUG_DIR)\WebServer$(FILE_SUFFIX_CONSOLE).c:   Classes\WebServer.bas Classes\WebServer.bi Interfaces\IRunnable.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HttpReader.bi Modules\Logger.bi Modules\Network.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi

$(OBJ_RELEASE_DIR)\WebServer$(FILE_SUFFIX_SERVICE).c: Classes\WebServer.bas Classes\WebServer.bi Interfaces\IRunnable.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HttpReader.bi Modules\Logger.bi Modules\Network.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi

$(OBJ_DEBUG_DIR)\WebServer$(FILE_SUFFIX_SERVICE).c:   Classes\WebServer.bas Classes\WebServer.bi Interfaces\IRunnable.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HttpReader.bi Modules\Logger.bi Modules\Network.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi

$(OBJ_RELEASE_DIR)\WebServer$(FILE_SUFFIX_TEST).c: Classes\WebServer.bas Classes\WebServer.bi Interfaces\IRunnable.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HttpReader.bi Modules\Logger.bi Modules\Network.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi

$(OBJ_DEBUG_DIR)\WebServer$(FILE_SUFFIX_TEST).c:   Classes\WebServer.bas Classes\WebServer.bi Interfaces\IRunnable.bi Classes\ClientRequest.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HttpReader.bi Modules\Logger.bi Modules\Network.bi Classes\NetworkStream.bi Interfaces\INetworkStream.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ServerResponse.bi Classes\ThreadPool.bi Interfaces\IThreadPool.bi Classes\IniConfiguration.bi Interfaces\IIniConfiguration.bi


$(OBJ_RELEASE_DIR)\WebSite$(FILE_SUFFIX_CONSOLE).c: Classes\WebSite.bas Classes\WebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\WebSite$(FILE_SUFFIX_CONSOLE).c:   Classes\WebSite.bas Classes\WebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\WebSite$(FILE_SUFFIX_SERVICE).c: Classes\WebSite.bas Classes\WebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\WebSite$(FILE_SUFFIX_SERVICE).c:   Classes\WebSite.bas Classes\WebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\WebSite$(FILE_SUFFIX_TEST).c: Classes\WebSite.bas Classes\WebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Classes\HeapBSTR.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\WebSite$(FILE_SUFFIX_TEST).c:   Classes\WebSite.bas Classes\WebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Headers\CharacterConstants.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\FileBuffer.bi Interfaces\IFileBuffer.bi Classes\HeapBSTR.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\WebSiteCollection$(FILE_SUFFIX_CONSOLE).c: Classes\WebSiteCollection.bas Classes\WebSiteCollection.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\WebSiteCollection$(FILE_SUFFIX_CONSOLE).c:   Classes\WebSiteCollection.bas Classes\WebSiteCollection.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\WebSiteCollection$(FILE_SUFFIX_SERVICE).c: Classes\WebSiteCollection.bas Classes\WebSiteCollection.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\WebSiteCollection$(FILE_SUFFIX_SERVICE).c:   Classes\WebSiteCollection.bas Classes\WebSiteCollection.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_RELEASE_DIR)\WebSiteCollection$(FILE_SUFFIX_TEST).c: Classes\WebSiteCollection.bas Classes\WebSiteCollection.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Modules\Logger.bi

$(OBJ_DEBUG_DIR)\WebSiteCollection$(FILE_SUFFIX_TEST).c:   Classes\WebSiteCollection.bas Classes\WebSiteCollection.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Modules\Http.bi Interfaces\IString.bi Modules\Mime.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Classes\ContainerOf.bi Modules\Logger.bi


$(OBJ_RELEASE_DIR)\WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).c: Classes\WriteErrorAsyncTask.bas Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\ServerResponse.bi Modules\WebUtils.bi
 
$(OBJ_DEBUG_DIR)\WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).c:   Classes\WriteErrorAsyncTask.bas Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\ServerResponse.bi Modules\WebUtils.bi

$(OBJ_RELEASE_DIR)\WriteErrorAsyncTask$(FILE_SUFFIX_SERVICE).c: Classes\WriteErrorAsyncTask.bas Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\ServerResponse.bi Modules\WebUtils.bi

$(OBJ_DEBUG_DIR)\WriteErrorAsyncTask$(FILE_SUFFIX_SERVICE).c:   Classes\WriteErrorAsyncTask.bas Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\ServerResponse.bi Modules\WebUtils.bi

$(OBJ_RELEASE_DIR)\WriteErrorAsyncTask$(FILE_SUFFIX_TEST).c: Classes\WriteErrorAsyncTask.bas Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\ServerResponse.bi Modules\WebUtils.bi

$(OBJ_DEBUG_DIR)\WriteErrorAsyncTask$(FILE_SUFFIX_TEST).c:   Classes\WriteErrorAsyncTask.bas Classes\WriteErrorAsyncTask.bi Interfaces\IWriteErrorAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ArrayStringWriter.bi Interfaces\IArrayStringWriter.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\MemoryBuffer.bi Interfaces\IMemoryBuffer.bi Classes\ServerResponse.bi Modules\WebUtils.bi


$(OBJ_RELEASE_DIR)\WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).c: Classes\WriteResponseAsyncTask.bas Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\ServerResponse.bi Modules\WebUtils.bi
 
$(OBJ_DEBUG_DIR)\WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).c:   Classes\WriteResponseAsyncTask.bas Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\ServerResponse.bi Modules\WebUtils.bi

$(OBJ_RELEASE_DIR)\WriteResponseAsyncTask$(FILE_SUFFIX_SERVICE).c: Classes\WriteResponseAsyncTask.bas Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\ServerResponse.bi Modules\WebUtils.bi

$(OBJ_DEBUG_DIR)\WriteResponseAsyncTask$(FILE_SUFFIX_SERVICE).c:   Classes\WriteResponseAsyncTask.bas Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\ServerResponse.bi Modules\WebUtils.bi

$(OBJ_RELEASE_DIR)\WriteResponseAsyncTask$(FILE_SUFFIX_TEST).c: Classes\WriteResponseAsyncTask.bas Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\ServerResponse.bi Modules\WebUtils.bi

$(OBJ_DEBUG_DIR)\WriteResponseAsyncTask$(FILE_SUFFIX_TEST).c:   Classes\WriteResponseAsyncTask.bas Classes\WriteResponseAsyncTask.bi Interfaces\IWriteResponseAsyncIoTask.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IHttpAsyncIoTask.bi Interfaces\IAsyncIoTask.bi Interfaces\IHttpProcessorCollection.bi Interfaces\IEnumHttpProcessor.bi Interfaces\IHttpAsyncProcessor.bi Interfaces\IHttpWriter.bi Interfaces\IBuffer.bi Modules\Mime.bi Interfaces\IServerResponse.bi Interfaces\IWebSite.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Classes\ReadRequestAsyncTask.bi Interfaces\IReadRequestAsyncIoTask.bi Classes\ClientRequest.bi Classes\ContainerOf.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Classes\HttpWriter.bi Interfaces\INetworkStream.bi Modules\Logger.bi Classes\ServerResponse.bi Modules\WebUtils.bi


$(OBJ_RELEASE_DIR)\ClientBuffer$(FILE_SUFFIX_CONSOLE).c: Modules\ClientBuffer.bas Modules\ClientBuffer.bi

$(OBJ_DEBUG_DIR)\ClientBuffer$(FILE_SUFFIX_CONSOLE).c:   Modules\ClientBuffer.bas Modules\ClientBuffer.bi

$(OBJ_RELEASE_DIR)\ClientBuffer$(FILE_SUFFIX_SERVICE).c: Modules\ClientBuffer.bas Modules\ClientBuffer.bi

$(OBJ_DEBUG_DIR)\ClientBuffer$(FILE_SUFFIX_SERVICE).c:   Modules\ClientBuffer.bas Modules\ClientBuffer.bi

$(OBJ_RELEASE_DIR)\ClientBuffer$(FILE_SUFFIX_TEST).c: Modules\ClientBuffer.bas Modules\ClientBuffer.bi

$(OBJ_DEBUG_DIR)\ClientBuffer$(FILE_SUFFIX_TEST).c:   Modules\ClientBuffer.bas Modules\ClientBuffer.bi


$(OBJ_RELEASE_DIR)\ConsoleMain$(FILE_SUFFIX_CONSOLE).c: Modules\ConsoleMain.bas Classes\CreateInstance.bi Modules\Logger.bi Classes\WebServer.bi Interfaces\IRunnable.bi

$(OBJ_DEBUG_DIR)\ConsoleMain$(FILE_SUFFIX_CONSOLE).c:   Modules\ConsoleMain.bas Classes\CreateInstance.bi Modules\Logger.bi Classes\WebServer.bi Interfaces\IRunnable.bi


$(OBJ_RELEASE_DIR)\Http$(FILE_SUFFIX_CONSOLE).c: Modules\Http.bas Modules\Http.bi

$(OBJ_DEBUG_DIR)\Http$(FILE_SUFFIX_CONSOLE).c:   Modules\Http.bas Modules\Http.bi

$(OBJ_RELEASE_DIR)\Http$(FILE_SUFFIX_SERVICE).c: Modules\Http.bas Modules\Http.bi

$(OBJ_DEBUG_DIR)\Http$(FILE_SUFFIX_SERVICE).c:   Modules\Http.bas Modules\Http.bi

$(OBJ_RELEASE_DIR)\Http$(FILE_SUFFIX_TEST).c: Modules\Http.bas Modules\Http.bi

$(OBJ_DEBUG_DIR)\Http$(FILE_SUFFIX_TEST).c:   Modules\Http.bas Modules\Http.bi


$(OBJ_RELEASE_DIR)\Logger$(FILE_SUFFIX_CONSOLE).c: Modules\Logger.bas Modules\Logger.bi

$(OBJ_DEBUG_DIR)\Logger$(FILE_SUFFIX_CONSOLE).c:   Modules\Logger.bas Modules\Logger.bi

$(OBJ_RELEASE_DIR)\Logger$(FILE_SUFFIX_SERVICE).c: Modules\Logger.bas Modules\Logger.bi

$(OBJ_DEBUG_DIR)\Logger$(FILE_SUFFIX_SERVICE).c:   Modules\Logger.bas Modules\Logger.bi

$(OBJ_RELEASE_DIR)\Logger$(FILE_SUFFIX_TEST).c: Modules\Logger.bas Modules\Logger.bi

$(OBJ_DEBUG_DIR)\Logger$(FILE_SUFFIX_TEST).c:   Modules\Logger.bas Modules\Logger.bi


$(OBJ_RELEASE_DIR)\Mime$(FILE_SUFFIX_CONSOLE).c: Modules\Mime.bas Modules\Mime.bi

$(OBJ_DEBUG_DIR)\Mime$(FILE_SUFFIX_CONSOLE).c:   Modules\Mime.bas Modules\Mime.bi

$(OBJ_RELEASE_DIR)\Mime$(FILE_SUFFIX_SERVICE).c: Modules\Mime.bas Modules\Mime.bi

$(OBJ_DEBUG_DIR)\Mime$(FILE_SUFFIX_SERVICE).c:   Modules\Mime.bas Modules\Mime.bi

$(OBJ_RELEASE_DIR)\Mime$(FILE_SUFFIX_TEST).c: Modules\Mime.bas Modules\Mime.bi

$(OBJ_DEBUG_DIR)\Mime$(FILE_SUFFIX_TEST).c:   Modules\Mime.bas Modules\Mime.bi


$(OBJ_RELEASE_DIR)\Network$(FILE_SUFFIX_CONSOLE).c: Modules\Network.bas Modules\Network.bi

$(OBJ_DEBUG_DIR)\Network$(FILE_SUFFIX_CONSOLE).c:   Modules\Network.bas Modules\Network.bi

$(OBJ_RELEASE_DIR)\Network$(FILE_SUFFIX_SERVICE).c: Modules\Network.bas Modules\Network.bi

$(OBJ_DEBUG_DIR)\Network$(FILE_SUFFIX_SERVICE).c:   Modules\Network.bas Modules\Network.bi

$(OBJ_RELEASE_DIR)\Network$(FILE_SUFFIX_TEST).c: Modules\Network.bas Modules\Network.bi

$(OBJ_DEBUG_DIR)\Network$(FILE_SUFFIX_TEST).c:   Modules\Network.bas Modules\Network.bi


$(OBJ_RELEASE_DIR)\TestMain$(FILE_SUFFIX_TEST).c: Modules\TestMain.bas

$(OBJ_DEBUG_DIR)\TestMain$(FILE_SUFFIX_TEST).c:   Modules\TestMain.bas


$(OBJ_RELEASE_DIR)\WebUtils$(FILE_SUFFIX_CONSOLE).c: Modules\WebUtils.bas Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Modules\Mime.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Headers\StringConstants.bi

$(OBJ_DEBUG_DIR)\WebUtils$(FILE_SUFFIX_CONSOLE).c:   Modules\WebUtils.bas Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Modules\Mime.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Headers\StringConstants.bi

$(OBJ_RELEASE_DIR)\WebUtils$(FILE_SUFFIX_SERVICE).c: Modules\WebUtils.bas Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Modules\Mime.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Headers\StringConstants.bi

$(OBJ_DEBUG_DIR)\WebUtils$(FILE_SUFFIX_SERVICE).c:   Modules\WebUtils.bas Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Modules\Mime.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Headers\StringConstants.bi

$(OBJ_RELEASE_DIR)\WebUtils$(FILE_SUFFIX_TEST).c: Modules\WebUtils.bas Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Modules\Mime.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Headers\StringConstants.bi

$(OBJ_DEBUG_DIR)\WebUtils$(FILE_SUFFIX_TEST).c:   Modules\WebUtils.bas Modules\WebUtils.bi Interfaces\IClientRequest.bi Interfaces\IClientUri.bi Interfaces\IString.bi Modules\Http.bi Interfaces\IHttpReader.bi Interfaces\IAsyncResult.bi Interfaces\IBaseStream.bi Interfaces\IServerResponse.bi Modules\Mime.bi Interfaces\IWebSiteCollection.bi Interfaces\IEnumWebSite.bi Interfaces\IWebSite.bi Interfaces\IBuffer.bi Headers\CharacterConstants.bi Classes\CreateInstance.bi Classes\HeapBSTR.bi Headers\StringConstants.bi


$(OBJ_RELEASE_DIR)\WindowsServiceMain$(FILE_SUFFIX_SERVICE).c: Modules\WindowsServiceMain.bas Classes\CreateInstance.bi Modules\Logger.bi Classes\WebServer.bi Interfaces\IRunnable.bi

$(OBJ_DEBUG_DIR)\WindowsServiceMain$(FILE_SUFFIX_SERVICE).c:   Modules\WindowsServiceMain.bas Classes\CreateInstance.bi Modules\Logger.bi Classes\WebServer.bi Interfaces\IRunnable.bi


$(OBJ_RELEASE_DIR)\EntryPoint$(FILE_SUFFIX_CONSOLE).c: Modules\EntryPoint.bas

$(OBJ_DEBUG_DIR)\EntryPoint$(FILE_SUFFIX_CONSOLE).c:   Modules\EntryPoint.bas

$(OBJ_RELEASE_DIR)\EntryPoint$(FILE_SUFFIX_SERVICE).c: Modules\EntryPoint.bas

$(OBJ_DEBUG_DIR)\EntryPoint$(FILE_SUFFIX_SERVICE).c:   Modules\EntryPoint.bas

$(OBJ_RELEASE_DIR)\EntryPoint$(FILE_SUFFIX_TEST).c: Modules\EntryPoint.bas

$(OBJ_DEBUG_DIR)\EntryPoint$(FILE_SUFFIX_TEST).c:   Modules\EntryPoint.bas


$(OBJ_RELEASE_DIR)\Resources$(FILE_SUFFIX_CONSOLE).obj: Resources\Resources.RC Resources\Resources.RH Resources\app.exe.manifest

$(OBJ_DEBUG_DIR)\Resources$(FILE_SUFFIX_CONSOLE).obj: Resources\Resources.RC Resources\Resources.RH Resources\app.exe.manifest

$(OBJ_RELEASE_DIR)\Resources$(FILE_SUFFIX_SERVICE).obj: Resources\Resources.RC Resources\Resources.RH Resources\app.exe.manifest

$(OBJ_DEBUG_DIR)\Resources$(FILE_SUFFIX_SERVICE).obj: Resources\Resources.RC Resources\Resources.RH Resources\app.exe.manifest

$(OBJ_RELEASE_DIR)\Resources$(FILE_SUFFIX_TEST).obj: Resources\Resources.RC Resources\Resources.RH Resources\app.exe.manifest

$(OBJ_DEBUG_DIR)\Resources$(FILE_SUFFIX_TEST).obj: Resources\Resources.RC Resources\Resources.RH Resources\app.exe.manifest

