# Dependencies

$(OBJ_RELEASE_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)AcceptConnectionAsyncTask.bi src$(PATH_SEP)IAcceptConnectionAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapMemoryAllocator.bi src$(PATH_SEP)IHeapMemoryAllocator.bi src$(PATH_SEP)HttpReader.bi src$(PATH_SEP)NetworkStream.bi src$(PATH_SEP)INetworkStream.bi src$(PATH_SEP)ReadRequestAsyncTask.bi src$(PATH_SEP)IReadRequestAsyncIoTask.bi src$(PATH_SEP)TcpListener.bi src$(PATH_SEP)ITcpListener.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)AcceptConnectionAsyncTask.bi src$(PATH_SEP)IAcceptConnectionAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapMemoryAllocator.bi src$(PATH_SEP)IHeapMemoryAllocator.bi src$(PATH_SEP)HttpReader.bi src$(PATH_SEP)NetworkStream.bi src$(PATH_SEP)INetworkStream.bi src$(PATH_SEP)ReadRequestAsyncTask.bi src$(PATH_SEP)IReadRequestAsyncIoTask.bi src$(PATH_SEP)TcpListener.bi src$(PATH_SEP)ITcpListener.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)ArrayStringWriter.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)ArrayStringWriter.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)ContainerOf.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)ContainerOf.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)ClientRequest.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ClientUri.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)ClientRequest.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ClientUri.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)ClientUri.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)Http.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)ClientUri.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)Http.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)FileStream$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)FileStream.bi src$(PATH_SEP)IFileStream.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)FileStream$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)FileStream.bi src$(PATH_SEP)IFileStream.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX).$(C_EXT): 

$(OBJ_DEBUG_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX).$(C_EXT):   


$(OBJ_RELEASE_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)ContainerOf.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)ContainerOf.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)HeapMemoryAllocator.bi src$(PATH_SEP)IHeapMemoryAllocator.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)Logger.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)HeapMemoryAllocator.bi src$(PATH_SEP)IHeapMemoryAllocator.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)Logger.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)HttpGetProcessor.bi src$(PATH_SEP)IHttpGetAsyncProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)ArrayStringWriter.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi
 
$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)HttpGetProcessor.bi src$(PATH_SEP)IHttpGetAsyncProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)ArrayStringWriter.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)HttpOptionsProcessor.bi src$(PATH_SEP)IHttpOptionsAsyncProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)MemoryStream.bi src$(PATH_SEP)IMemoryStream.bi
 
$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)HttpOptionsProcessor.bi src$(PATH_SEP)IHttpOptionsAsyncProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)MemoryStream.bi src$(PATH_SEP)IMemoryStream.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)HttpProcessorCollection.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi
 
$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)HttpProcessorCollection.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpPutProcessor$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)HttpPutProcessor.bi src$(PATH_SEP)IHttpPutAsyncProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)ArrayStringWriter.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi
 
$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpPutProcessor$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)HttpPutProcessor.bi src$(PATH_SEP)IHttpPutAsyncProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)ArrayStringWriter.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)HttpReader.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)HeapBSTR.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)HttpReader.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)HeapBSTR.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)HttpTraceProcessor.bi src$(PATH_SEP)IHttpTraceAsyncProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)MemoryStream.bi src$(PATH_SEP)IMemoryStream.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)HttpTraceProcessor.bi src$(PATH_SEP)IHttpTraceAsyncProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)MemoryStream.bi src$(PATH_SEP)IMemoryStream.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HttpWriter.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)ThreadPool.bi src$(PATH_SEP)IThreadPool.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HttpWriter.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)ThreadPool.bi src$(PATH_SEP)IThreadPool.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)IniConfiguration.bi src$(PATH_SEP)IIniConfiguration.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)HttpGetProcessor.bi src$(PATH_SEP)IHttpGetAsyncProcessor.bi src$(PATH_SEP)HttpOptionsProcessor.bi src$(PATH_SEP)IHttpOptionsAsyncProcessor.bi src$(PATH_SEP)HttpPutProcessor.bi src$(PATH_SEP)IHttpPutAsyncProcessor.bi src$(PATH_SEP)HttpProcessorCollection.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)HttpTraceProcessor.bi src$(PATH_SEP)IHttpTraceAsyncProcessor.bi src$(PATH_SEP)WebSite.bi src$(PATH_SEP)WebSiteCollection.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)IniConfiguration.bi src$(PATH_SEP)IIniConfiguration.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)HttpGetProcessor.bi src$(PATH_SEP)IHttpGetAsyncProcessor.bi src$(PATH_SEP)HttpOptionsProcessor.bi src$(PATH_SEP)IHttpOptionsAsyncProcessor.bi src$(PATH_SEP)HttpPutProcessor.bi src$(PATH_SEP)IHttpPutAsyncProcessor.bi src$(PATH_SEP)HttpProcessorCollection.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)HttpTraceProcessor.bi src$(PATH_SEP)IHttpTraceAsyncProcessor.bi src$(PATH_SEP)WebSite.bi src$(PATH_SEP)WebSiteCollection.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)MemoryStream$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)MemoryStream.bi src$(PATH_SEP)IMemoryStream.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)ThreadPool.bi src$(PATH_SEP)IThreadPool.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)MemoryStream$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)MemoryStream.bi src$(PATH_SEP)IMemoryStream.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)ThreadPool.bi src$(PATH_SEP)IThreadPool.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)NetworkStream.bi src$(PATH_SEP)INetworkStream.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)Network.bi
 
$(OBJ_DEBUG_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)NetworkStream.bi src$(PATH_SEP)INetworkStream.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)Network.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)ReadRequestAsyncTask.bi src$(PATH_SEP)IReadRequestAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)ClientRequest.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)WriteErrorAsyncTask.bi src$(PATH_SEP)WriteResponseAsyncTask.bi src$(PATH_SEP)IWriteResponseAsyncIoTask.bi
 
$(OBJ_DEBUG_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)ReadRequestAsyncTask.bi src$(PATH_SEP)IReadRequestAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)ClientRequest.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)WriteErrorAsyncTask.bi src$(PATH_SEP)WriteResponseAsyncTask.bi src$(PATH_SEP)IWriteResponseAsyncIoTask.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)ServerResponse.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)ArrayStringWriter.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)ServerResponse.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)ArrayStringWriter.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)TcpListener.bi src$(PATH_SEP)ITcpListener.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)Network.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)TcpListener.bi src$(PATH_SEP)ITcpListener.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)AsyncResult.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)Network.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)ThreadPool.bi src$(PATH_SEP)IThreadPool.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)Logger.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)ThreadPool.bi src$(PATH_SEP)IThreadPool.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)Logger.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)WebServer.bi src$(PATH_SEP)IWebServer.bi src$(PATH_SEP)AcceptConnectionAsyncTask.bi src$(PATH_SEP)IAcceptConnectionAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)HttpReader.bi src$(PATH_SEP)Network.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi
 
$(OBJ_DEBUG_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)WebServer.bi src$(PATH_SEP)IWebServer.bi src$(PATH_SEP)AcceptConnectionAsyncTask.bi src$(PATH_SEP)IAcceptConnectionAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)HttpReader.bi src$(PATH_SEP)Network.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)WebSite.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)ArrayStringWriter.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)FileStream.bi src$(PATH_SEP)IFileStream.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)MemoryStream.bi src$(PATH_SEP)IMemoryStream.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)WebSite.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)ArrayStringWriter.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)FileStream.bi src$(PATH_SEP)IFileStream.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)MemoryStream.bi src$(PATH_SEP)IMemoryStream.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)WebSiteCollection.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)ContainerOf.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)WebSiteCollection.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)ContainerOf.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)WriteErrorAsyncTask.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)ReadRequestAsyncTask.bi src$(PATH_SEP)IReadRequestAsyncIoTask.bi src$(PATH_SEP)ClientRequest.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)HttpProcessorCollection.bi src$(PATH_SEP)HttpWriter.bi src$(PATH_SEP)ServerResponse.bi src$(PATH_SEP)WebsiteCollection.bi src$(PATH_SEP)WebUtils.bi
 
$(OBJ_DEBUG_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)WriteErrorAsyncTask.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)ReadRequestAsyncTask.bi src$(PATH_SEP)IReadRequestAsyncIoTask.bi src$(PATH_SEP)ClientRequest.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)HttpProcessorCollection.bi src$(PATH_SEP)HttpWriter.bi src$(PATH_SEP)ServerResponse.bi src$(PATH_SEP)WebsiteCollection.bi src$(PATH_SEP)WebUtils.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)WriteResponseAsyncTask.bi src$(PATH_SEP)IWriteResponseAsyncIoTask.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)ReadRequestAsyncTask.bi src$(PATH_SEP)IReadRequestAsyncIoTask.bi src$(PATH_SEP)ClientRequest.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)HttpProcessorCollection.bi src$(PATH_SEP)HttpWriter.bi src$(PATH_SEP)ServerResponse.bi src$(PATH_SEP)WebsiteCollection.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi
 
$(OBJ_DEBUG_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)WriteResponseAsyncTask.bi src$(PATH_SEP)IWriteResponseAsyncIoTask.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)ReadRequestAsyncTask.bi src$(PATH_SEP)IReadRequestAsyncIoTask.bi src$(PATH_SEP)ClientRequest.bi src$(PATH_SEP)ContainerOf.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)HttpProcessorCollection.bi src$(PATH_SEP)HttpWriter.bi src$(PATH_SEP)ServerResponse.bi src$(PATH_SEP)WebsiteCollection.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)HeapBSTR.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)HeapBSTR.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)ConsoleMain.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)ConsoleMain.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)Http$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)Http.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)Http$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)Http.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)Logger.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)Logger.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)Mime.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)Mime.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)Network$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)Network.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)Network$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)Network.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)HeapMemoryAllocator.bi src$(PATH_SEP)IHeapMemoryAllocator.bi src$(PATH_SEP)HttpProcessorCollection.bi src$(PATH_SEP)IniConfiguration.bi src$(PATH_SEP)IIniConfiguration.bi src$(PATH_SEP)Logger.bi src$(PATH_SEP)ThreadPool.bi src$(PATH_SEP)IThreadPool.bi src$(PATH_SEP)WebSiteCollection.bi src$(PATH_SEP)WriteErrorAsyncTask.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)CharacterConstants.bi src$(PATH_SEP)HeapBSTR.bi src$(PATH_SEP)HeapMemoryAllocator.bi src$(PATH_SEP)IHeapMemoryAllocator.bi src$(PATH_SEP)HttpProcessorCollection.bi src$(PATH_SEP)IniConfiguration.bi src$(PATH_SEP)IIniConfiguration.bi src$(PATH_SEP)Logger.bi src$(PATH_SEP)ThreadPool.bi src$(PATH_SEP)IThreadPool.bi src$(PATH_SEP)WebSiteCollection.bi src$(PATH_SEP)WriteErrorAsyncTask.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)WindowsServiceMain.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)WindowsServiceMain.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX).$(C_EXT): src$(PATH_SEP)ConsoleMain.bi src$(PATH_SEP)Network.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)WindowsServiceMain.bi

$(OBJ_DEBUG_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX).$(C_EXT):   src$(PATH_SEP)ConsoleMain.bi src$(PATH_SEP)Network.bi src$(PATH_SEP)WebUtils.bi src$(PATH_SEP)IAsyncIoTask.bi src$(PATH_SEP)IAsyncResult.bi src$(PATH_SEP)IClientRequest.bi src$(PATH_SEP)IClientUri.bi src$(PATH_SEP)IString.bi src$(PATH_SEP)Http.bi src$(PATH_SEP)IHttpReader.bi src$(PATH_SEP)ClientBuffer.bi src$(PATH_SEP)IBaseStream.bi src$(PATH_SEP)IServerResponse.bi src$(PATH_SEP)Mime.bi src$(PATH_SEP)IWriteErrorAsyncIoTask.bi src$(PATH_SEP)IHttpAsyncIoTask.bi src$(PATH_SEP)IHttpProcessorCollection.bi src$(PATH_SEP)IEnumHttpProcessor.bi src$(PATH_SEP)IHttpAsyncProcessor.bi src$(PATH_SEP)IHttpWriter.bi src$(PATH_SEP)IAttributedStream.bi src$(PATH_SEP)IWebSite.bi src$(PATH_SEP)IWebSiteCollection.bi src$(PATH_SEP)IEnumWebSite.bi src$(PATH_SEP)WindowsServiceMain.bi


$(OBJ_RELEASE_DIR)$(PATH_SEP)Resources$(FILE_SUFFIX).$(OBJ_EXT): src$(PATH_SEP)Resources.RH src$(PATH_SEP)app.exe.manifest

$(OBJ_DEBUG_DIR)$(PATH_SEP)Resources$(FILE_SUFFIX).$(OBJ_EXT): src$(PATH_SEP)Resources.RH src$(PATH_SEP)app.exe.manifest
