.PHONY: all debug release clean

ifeq ($(WITHOUT_RUNTIME_FLAG),true)
WITHOUT_RUNTIME_DEFINED=-d WITHOUT_RUNTIME
WITHOUT_RUNTIME_SUFFIX=-Rt
GUIDS_WITHOUT_MINGW_SUFFIX=-Mingw
OBJECTFILES_CRUNTIME_ST=
OBJECTFILES_CRUNTIME_MT=
LIBRARIES_FBRUNTIME_ST=
LIBRARIES_FBRUNTIME_MT=
LIBRARIES_GCCRUNTIME=
else
WITHOUT_RUNTIME_DEFINED=
WITHOUT_RUNTIME_SUFFIX=+Rt
GUIDS_WITHOUT_MINGW_SUFFIX=+Mingw
OBJECTFILES_CRUNTIME_ST="crt2.o" "crtbegin.o" "crtend.o" "fbrt0.o"
OBJECTFILES_CRUNTIME_MT=$(OBJECTFILES_CRUNTIME_ST) "gcrt2.o"
LIBRARIES_FBRUNTIME_ST=-lfb
LIBRARIES_FBRUNTIME_MT=-lfbmt
LIBRARIES_GCCRUNTIME=-lgcc -lmingw32 -lmingwex -lmoldname -lgcc_eh
endif

ifeq ($(MULTITHREAD_RUNTIME_FLAG),true)
LIBRARIES_FBRUNTIME=$(LIBRARIES_FBRUNTIME_MT)
OBJECTFILES_CRUNTIME=$(OBJECTFILES_CRUNTIME_MT)
else
LIBRARIES_FBRUNTIME=$(LIBRARIES_FBRUNTIME_ST)
OBJECTFILES_CRUNTIME=$(OBJECTFILES_CRUNTIME_ST)
endif

FILE_SUFFIX_BASE=_$(GCC_VER)_$(FBC_VER)_$(WITHOUT_RUNTIME_SUFFIX)
FILE_SUFFIX_CONSOLE=_Console$(FILE_SUFFIX_BASE)

CODE_GENERATION_BACKEND=gcc

BIN_DEBUG_DIR_64=bin$(PATH_SEP)Debug$(PATH_SEP)x64
BIN_RELEASE_DIR_64=bin$(PATH_SEP)Release$(PATH_SEP)x64
OBJ_DEBUG_DIR_64=obj$(PATH_SEP)Debug$(PATH_SEP)x64
OBJ_RELEASE_DIR_64=obj$(PATH_SEP)Release$(PATH_SEP)x64

BIN_DEBUG_DIR_86=bin$(PATH_SEP)Debug$(PATH_SEP)x86
BIN_RELEASE_DIR_86=bin$(PATH_SEP)Release$(PATH_SEP)x86
OBJ_DEBUG_DIR_86=obj$(PATH_SEP)Debug$(PATH_SEP)x86
OBJ_RELEASE_DIR_86=obj$(PATH_SEP)Release$(PATH_SEP)x86

BIN_DEBUG_DIR_64_MOVE=bin$(MOVE_PATH_SEP)Debug$(MOVE_PATH_SEP)x64
BIN_RELEASE_DIR_64_MOVE=bin$(MOVE_PATH_SEP)Release$(MOVE_PATH_SEP)x64
OBJ_DEBUG_DIR_64_MOVE=obj$(MOVE_PATH_SEP)Debug$(MOVE_PATH_SEP)x64
OBJ_RELEASE_DIR_64_MOVE=obj$(MOVE_PATH_SEP)Release$(MOVE_PATH_SEP)x64

BIN_DEBUG_DIR_86_MOVE=bin$(MOVE_PATH_SEP)Debug$(MOVE_PATH_SEP)x86
BIN_RELEASE_DIR_86_MOVE=bin$(MOVE_PATH_SEP)Release$(MOVE_PATH_SEP)x86
OBJ_DEBUG_DIR_86_MOVE=obj$(MOVE_PATH_SEP)Debug$(MOVE_PATH_SEP)x86
OBJ_RELEASE_DIR_86_MOVE=obj$(MOVE_PATH_SEP)Release$(MOVE_PATH_SEP)x86

ifeq ($(PROCESSOR_ARCHITECTURE),AMD64)

GCC_ARCHITECTURE=-m64 -march=native
TARGET_ASSEMBLER_ARCH=--64
ifeq ($(WITHOUT_RUNTIME_FLAG),true)
ENTRY_POINT_PARAM=-e ENTRYPOINT
else
ENTRY_POINT_PARAM=
endif
PE_FILE_FORMAT=i386pep
ResourceCompilerBitFlag=/machine X64
BIN_DEBUG_DIR=$(BIN_DEBUG_DIR_64)
BIN_RELEASE_DIR=$(BIN_RELEASE_DIR_64)
OBJ_DEBUG_DIR=$(OBJ_DEBUG_DIR_64)
OBJ_RELEASE_DIR=$(OBJ_RELEASE_DIR_64)
BIN_DEBUG_DIR_MOVE=$(BIN_DEBUG_DIR_64)
BIN_RELEASE_DIR_MOVE=$(BIN_RELEASE_DIR_64)
OBJ_DEBUG_DIR_MOVE=$(OBJ_DEBUG_DIR_64)
OBJ_RELEASE_DIR_MOVE=$(OBJ_RELEASE_DIR_64)

else

GCC_ARCHITECTURE=-m32 -march=native
TARGET_ASSEMBLER_ARCH=--32
ifeq ($(WITHOUT_RUNTIME_FLAG),true)
ENTRY_POINT_PARAM=-e _ENTRYPOINT@0
else
ENTRY_POINT_PARAM=
endif
PE_FILE_FORMAT=i386pe --large-address-aware
ResourceCompilerBitFlag=/nw
BIN_DEBUG_DIR=$(BIN_DEBUG_DIR_86)
BIN_RELEASE_DIR=$(BIN_RELEASE_DIR_86)
OBJ_DEBUG_DIR=$(OBJ_DEBUG_DIR_86)
OBJ_RELEASE_DIR=$(OBJ_RELEASE_DIR_86)
BIN_DEBUG_DIR_MOVE=$(BIN_DEBUG_DIR_86)
BIN_RELEASE_DIR_MOVE=$(BIN_RELEASE_DIR_86)
OBJ_DEBUG_DIR_MOVE=$(OBJ_DEBUG_DIR_86)
OBJ_RELEASE_DIR_MOVE=$(OBJ_RELEASE_DIR_86)

endif

FBC ?= fbc.exe
FBCFLAGS+=$(WITHOUT_RUNTIME_DEFINED) -gen $(CODE_GENERATION_BACKEND) -i src -r -O 0 -s console
FBCFLAGS_DEBUG+=$(FBCFLAGS) -g

CC ?= gcc.exe
# CFLAGS
# CFLAGS_DEBUG
# EXTRA_CFLAGS=-O2 -Wall -Werror
# CFLAGS+= ${EXTRA_CFLAGS} -I. -Isubdir
# ${CC} ${EXTRA_CFLAGS} ${CPPFLAGS} ${CFLAGS} -o $@ $< ${LDADD}

AS ?= as.exe
# ASFLAGS
# ASFLAGS_DEBUG
# $(AS) $(ASFLAGS)

AR ?= ar.exe
# ARFLAGS

GORC ?= GoRC.exe
# GORCFLAGS

LD ?= ld.exe
# LDFLAGS
# LDLIBS
# LD_DEBUG

# OBJECTS
# OBJECTS_DIR

LIBRARIES_UUID=-luuid
LIBRARIES_WINAPI=-ladvapi32 -lkernel32 -lmsvcrt -lmswsock -lole32 -loleaut32 -lshell32 -lshlwapi -lws2_32
LIBRARIES_BASE=$(LIBRARIES_GCCRUNTIME) $(LIBRARIES_FBRUNTIME) $(LIBRARIES_WINAPI) $(LIBRARIES_UUID)
LIBRARIES_ALL=$(LIBRARIES_BASE) -lGuids$(FILE_SUFFIX_BASE)

# -Wno-unused-but-set-variable
# -fwrapv
# -Wno-format
# -Wextra
GCC_COMPILER_WARNINGS=-Wall -Werror -Wno-unused-label -Wno-unused-function -Wno-unused-variable -Wno-main -Werror-implicit-function-declaration
GCC_COMPILER_OPTIMIZATIONS=-fdata-sections -ffunction-sections -mno-stack-arg-probe -fno-stack-check -fno-stack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables
GCC_COMPILER_PARAMETERS_BASE=$(GCC_COMPILER_WARNINGS) -nostdlib -nostdinc -fno-strict-aliasing -frounding-math -fno-math-errno -fno-exceptions -fno-ident

GCC_COMPILER_PARAMETERS_RELEASE=$(GCC_COMPILER_PARAMETERS_BASE) $(GCC_ARCHITECTURE) $(GCC_COMPILER_OPTIMIZATIONS) -masm=intel -S -Ofast
GCC_COMPILER_PARAMETERS_DEBUG=  $(GCC_COMPILER_PARAMETERS_BASE) $(GCC_ARCHITECTURE) -masm=intel -S -g -Og

GCC_ASSEMBLER_PARAMETERS_RELEASE=$(TARGET_ASSEMBLER_ARCH) --strip-local-absolute
GCC_ASSEMBLER_PARAMETERS_DEBUG=  $(TARGET_ASSEMBLER_ARCH)

GCC_LINKER_PARAMETERS_BASE=-m $(PE_FILE_FORMAT) -subsystem console $(ENTRY_POINT_PARAM) --stack 1048576,1048576 --major-image-version 1 --minor-image-version 0 --no-seh --nxcompat -L "$(LIB_DIR)"
# --print-gc-sections
GCC_LINKER_PARAMETERS_RELEASE=$(GCC_LINKER_PARAMETERS_BASE) -s --gc-sections
GCC_LINKER_PARAMETERS_DEBUG=  $(GCC_LINKER_PARAMETERS_BASE)



OUTPUT_FILE_NAME_CONSOLE=Station922$(FILE_SUFFIX_CONSOLE).exe

OBJECTFILES_GUIDS_RELEASE=$(OBJ_RELEASE_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).o
OBJECTFILES_GUIDS_DEBUG=  $(OBJ_DEBUG_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).o

OBJECTFILES_RELEASE_CONSOLE_OBJECTS_COM=$(OBJ_RELEASE_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).o 
OBJECTFILES_DEBUG_CONSOLE_OBJECTS_COM=  $(OBJ_DEBUG_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).o   

OBJECTFILES_RELEASE_CONSOLE_MODULES=$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).o 
OBJECTFILES_DEBUG_CONSOLE_MODULES=  $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).o   

OBJECTFILES_RELEASE_CONSOLE_RESOURCES=$(OBJ_RELEASE_DIR)$(PATH_SEP)Resources$(FILE_SUFFIX_CONSOLE).obj
OBJECTFILES_DEBUG_CONSOLE_RESOURCES=  $(OBJ_DEBUG_DIR)$(PATH_SEP)Resources$(FILE_SUFFIX_CONSOLE).obj

OBJECTFILES_RELEASE_CONSOLE_BASE=$(OBJECTFILES_RELEASE_CONSOLE_OBJECTS_COM) $(OBJECTFILES_RELEASE_CONSOLE_MODULES) $(OBJECTFILES_RELEASE_CONSOLE_RESOURCES)
OBJECTFILES_DEBUG_CONSOLE_BASE=  $(OBJECTFILES_DEBUG_CONSOLE_OBJECTS_COM)   $(OBJECTFILES_DEBUG_CONSOLE_MODULES)   $(OBJECTFILES_DEBUG_CONSOLE_RESOURCES)

OBJECTFILES_RELEASE_CONSOLE=$(OBJECTFILES_RELEASE_CONSOLE_BASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).o $(OBJ_RELEASE_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).o
OBJECTFILES_DEBUG_CONSOLE=  $(OBJECTFILES_DEBUG_CONSOLE_BASE)   $(OBJ_DEBUG_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).o   $(OBJ_DEBUG_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).o  



all: $(BIN_RELEASE_DIR)$(PATH_SEP)$(OUTPUT_FILE_NAME_CONSOLE) $(BIN_DEBUG_DIR)$(PATH_SEP)$(OUTPUT_FILE_NAME_CONSOLE)

release: $(BIN_RELEASE_DIR)$(PATH_SEP)$(OUTPUT_FILE_NAME_CONSOLE)

debug: $(BIN_DEBUG_DIR)$(PATH_SEP)$(OUTPUT_FILE_NAME_CONSOLE)

clean:
	echo $(DELETE_COMMAND) %AllFileWithExtensionC% %AllFileWithExtensionAsm% %AllObjectFiles%

include dependencies.mk



$(BIN_RELEASE_DIR)$(PATH_SEP)$(OUTPUT_FILE_NAME_CONSOLE): $(OBJECTFILES_RELEASE_CONSOLE) $(OBJ_RELEASE_DIR)$(PATH_SEP)libGuids$(FILE_SUFFIX_BASE).a
	$(LD) $(GCC_LINKER_PARAMETERS_RELEASE) -L "$(OBJ_RELEASE_DIR)" $(OBJECTFILES_RELEASE_CONSOLE) $(LIBRARIES_ALL) -o "$(BIN_RELEASE_DIR)$(PATH_SEP)$(OUTPUT_FILE_NAME_CONSOLE)"

$(BIN_DEBUG_DIR)$(PATH_SEP)$(OUTPUT_FILE_NAME_CONSOLE):   $(OBJECTFILES_DEBUG_CONSOLE)   $(OBJ_DEBUG_DIR)$(PATH_SEP)libGuids$(FILE_SUFFIX_BASE).a
	$(LD) $(GCC_LINKER_PARAMETERS_DEBUG)   -L "$(OBJ_DEBUG_DIR)" $(OBJECTFILES_DEBUG_CONSOLE)   $(LIBRARIES_ALL) -lgcc -lmingw32 -lmingwex -lmoldname -lgcc_eh -o "$(BIN_DEBUG_DIR)$(PATH_SEP)$(OUTPUT_FILE_NAME_CONSOLE)"



$(OBJ_RELEASE_DIR)$(PATH_SEP)libGuids$(FILE_SUFFIX_BASE).a: $(OBJECTFILES_GUIDS_RELEASE)
	$(AR) -rsc $(OBJ_RELEASE_DIR)$(PATH_SEP)libGuids$(FILE_SUFFIX_BASE).a $(OBJECTFILES_GUIDS_RELEASE)

$(OBJ_DEBUG_DIR)$(PATH_SEP)libGuids$(FILE_SUFFIX_BASE).a: $(OBJECTFILES_GUIDS_DEBUG)
	$(AR) -rsc $(OBJ_DEBUG_DIR)$(PATH_SEP)libGuids$(FILE_SUFFIX_BASE).a $(OBJECTFILES_GUIDS_DEBUG)

$(OBJ_RELEASE_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).o: $(OBJ_DEBUG_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_DEBUG_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).asm: $(OBJ_DEBUG_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_DEBUG_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)Guids.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Guids.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)Guids$(FILE_SUFFIX_BASE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)Guids$(FILE_SUFFIX_BASE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)Guids.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Guids.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)Guids$(FILE_SUFFIX_BASE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)AcceptConnectionAsyncTask.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)AcceptConnectionAsyncTask.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)AcceptConnectionAsyncTask.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)AcceptConnectionAsyncTask.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)AcceptConnectionAsyncTask$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)ArrayStringWriter.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ArrayStringWriter.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)ArrayStringWriter.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ArrayStringWriter.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)ArrayStringWriter$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)AsyncResult.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)AsyncResult.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)AsyncResult.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)AsyncResult.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)AsyncResult$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)ClientRequest.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ClientRequest.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)ClientRequest.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ClientRequest.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)ClientRequest$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)ClientUri.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ClientUri.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)ClientUri.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ClientUri.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)ClientUri$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)CreateInstance.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)CreateInstance.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)CreateInstance.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)CreateInstance.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)CreateInstance$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)FileBuffer.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)FileBuffer.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)FileBuffer.bas"
	$(MOVE_COMMAND) src$(PATH_SEP)FileBuffer.c $(OBJ_DEBUG_DIR)$(PATH_SEP)FileBuffer$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)HeapBSTR.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HeapBSTR.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)HeapBSTR.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HeapBSTR.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)HeapBSTR$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)HeapMemoryAllocator.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HeapMemoryAllocator.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)HeapMemoryAllocator.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HeapMemoryAllocator.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)HeapMemoryAllocator$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)HttpGetProcessor.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpGetProcessor.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)HttpGetProcessor.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpGetProcessor.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)HttpGetProcessor$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)HttpOptionsProcessor.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpOptionsProcessor.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)HttpOptionsProcessor.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpOptionsProcessor.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)HttpOptionsProcessor$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)HttpProcessorCollection.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpProcessorCollection.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)HttpProcessorCollection.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpProcessorCollection.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)HttpProcessorCollection$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)HttpReader.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpReader.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)HttpReader.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpReader.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)HttpReader$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)HttpTraceProcessor.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpTraceProcessor.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)HttpTraceProcessor.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpTraceProcessor.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)HttpTraceProcessor$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)HttpWriter.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpWriter.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)HttpWriter.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)HttpWriter.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)HttpWriter$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)IniConfiguration.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)IniConfiguration.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)IniConfiguration.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)IniConfiguration.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)IniConfiguration$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)MemoryBuffer.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)MemoryBuffer.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)MemoryBuffer.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)MemoryBuffer.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)MemoryBuffer$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)NetworkStream.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)NetworkStream.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)NetworkStream.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)NetworkStream.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)NetworkStream$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)ReadRequestAsyncTask.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ReadRequestAsyncTask.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)ReadRequestAsyncTask.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ReadRequestAsyncTask.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)ReadRequestAsyncTask$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)ServerResponse.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ServerResponse.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)ServerResponse.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ServerResponse.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)ServerResponse$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)TcpListener.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)TcpListener.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)TcpListener.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)TcpListener.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)TcpListener$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)ThreadPool.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ThreadPool.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)ThreadPool.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ThreadPool.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)ThreadPool$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)WebServer.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WebServer.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)WebServer.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WebServer.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)WebServer$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)WebSite.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WebSite.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)WebSite.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WebSite.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)WebSite$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)WebSiteCollection.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WebSiteCollection.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)WebSiteCollection.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WebSiteCollection.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)WebSiteCollection$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)WriteErrorAsyncTask.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WriteErrorAsyncTask.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)WriteErrorAsyncTask.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WriteErrorAsyncTask.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)WriteErrorAsyncTask$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)WriteResponseAsyncTask.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WriteResponseAsyncTask.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)WriteResponseAsyncTask.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WriteResponseAsyncTask.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)WriteResponseAsyncTask$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)ClientBuffer.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ClientBuffer.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)ClientBuffer.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ClientBuffer.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)ClientBuffer$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)ConsoleMain.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ConsoleMain.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)ConsoleMain.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)ConsoleMain.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)ConsoleMain$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)Station922.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Station922.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)Station922.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Station922.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)Station922$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)Http.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Http.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)Http.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Http.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)Http$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)Logger.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Logger.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)Logger.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Logger.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)Logger$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)Mime.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Mime.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)Mime.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Mime.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)Mime$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)Network.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Network.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)Network.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Network.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)Network$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) "src$(PATH_SEP)WebUtils.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WebUtils.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) "src$(PATH_SEP)WebUtils.bas"
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WebUtils.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)WebUtils$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).o: $(OBJ_RELEASE_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).o

$(OBJ_DEBUG_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).o:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).asm
	$(AS) $(GCC_ASSEMBLER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).asm -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).o

$(OBJ_RELEASE_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).asm: $(OBJ_RELEASE_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_RELEASE) $(OBJ_RELEASE_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_RELEASE_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_DEBUG_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).asm:   $(OBJ_DEBUG_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).c
	$(CC) $(GCC_COMPILER_PARAMETERS_DEBUG) $(OBJ_DEBUG_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).c -o $(OBJ_DEBUG_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).asm

$(OBJ_RELEASE_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS) src$(PATH_SEP)WindowsServiceMain.bas
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WindowsServiceMain.c $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).c

$(OBJ_DEBUG_DIR)$(PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).c:
	$(FBC) $(FBCFLAGS_DEBUG) src$(PATH_SEP)WindowsServiceMain.bas
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)WindowsServiceMain.c $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)WindowsServiceMain$(FILE_SUFFIX_CONSOLE).c



$(OBJ_RELEASE_DIR)$(PATH_SEP)Resources$(FILE_SUFFIX_CONSOLE).obj:
	$(GORC) /d FROM_MAKEFILE          /ni $(ResourceCompilerBitFlag) /o /fo src$(PATH_SEP)Resources.obj src$(PATH_SEP)Resources.RC
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Resources.obj $(OBJ_RELEASE_DIR_MOVE)$(MOVE_PATH_SEP)Resources$(FILE_SUFFIX_CONSOLE).obj

$(OBJ_DEBUG_DIR)$(PATH_SEP)Resources$(FILE_SUFFIX_CONSOLE).obj:
	$(GORC) /d FROM_MAKEFILE /d DEBUG /ni $(ResourceCompilerBitFlag) /o /fo src$(PATH_SEP)Resources.obj src$(PATH_SEP)Resources.RC
	$(MOVE_COMMAND) src$(MOVE_PATH_SEP)Resources.obj $(OBJ_DEBUG_DIR_MOVE)$(MOVE_PATH_SEP)Resources$(FILE_SUFFIX_CONSOLE).obj

