set GCC_VERSION_SUFFIX=GCC810
set UNICODE_FLAG=true
set WITHOUT_RUNTIME_FLAG=true
set WITHOUT_CRITICAL_SECTIONS_FLAG=true
set PERFORMANCE_TESTING_FLAG=false
set MULTITHREAD_RUNTIME_FLAG=false
set FREEBASIC_COMPILER="%ProgramFiles%\FreeBASIC\fbc.exe"
set GCC_COMPILER=      "%ProgramFiles%\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\gcc.exe"
set GCC_ASSEMBLER=     "%ProgramFiles%\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\as.exe"
set GCC_LINKER=        "%ProgramFiles%\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\ld.exe"
set ARCHIVE_COMPILER=  "%ProgramFiles%\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\ar.exe"
set DLL_TOOL=          "%ProgramFiles%\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\dlltool.exe"
set RESOURCE_COMPILER= "%ProgramFiles%\FreeBASIC\bin\win64\GoRC.exe"
set COMPILER_LIB_PATH= "%ProgramFiles%\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\x86_64-w64-mingw32\lib"
set FB_EXTRA=          "%ProgramFiles%\FreeBASIC\lib\win64\fbextra.x"