set FREEBASIC_COMPILER_DIRECTORY=C:\Program Files (x86)\FreeBASIC-1.09.0-win64-gcc-9.3.0
set FREEBASIC_COMPILER_64="%FREEBASIC_COMPILER_DIRECTORY%\fbc64.exe"
set FREEBASIC_COMPILER_32="%FREEBASIC_COMPILER_DIRECTORY%\fbc32.exe"

%FREEBASIC_COMPILER_64% -m EntryPoint -x Station922_64.exe -O 3 *.bas *.rc
%FREEBASIC_COMPILER_32% -m EntryPoint -x Station922_86.exe -O 3 *.bas *.rc